export {default as homePage} from './homepage/index.js';
export {default as loginPage} from './loginpage/index.js';
export {default as dashboard} from "./dashboard/index.js";
export {default as DraftEmail} from "./draftEmail/index.js";
export {default as phishingLogs} from "./phishingLogs/index.js";
export {default as Clients} from "./clients/index.js";
export {default as pannel} from "./pannel/index.js"
export {default as aboutPage} from "./about/index.js"
 export {default as contacts} from "./contacts/index.js"
